# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EFF3E0
background         #161A16
cursor             #A1AC92

active_tab_foreground     #161A16
active_tab_background     #EFF3E0
inactive_tab_foreground   #EFF3E0
inactive_tab_background   #161A16

active_border_color   #EFF3E0
inactive_border_color #161A16
bell_border_color     #2F4042

color0      #3C413D
color1		#2F4042
color2		#3E4B33
color3		#3D4F55
color4		#646F51
color5		#9DA57C
color6		#9DA57C
color7		#E0E5CA
color8		#9CA08D
color9		#3E5658
color10		#536544
color11		#516972
color12		#85946B
color13		#D1DCA6
color14		#D1DCA6
color15		#E0E5CA
